server:
  port: 9005
spring:
  application:
    name: fleet-location-simulator
gpsSimmulator:
  googleApiKey: AIzaSyAKSzjFhBPdiLbVykYSLPLSyyPmdHRQSow

logging:
  level:
    org:
      apache:
        http=DEBUG:

---
spring:
  profiles: test
ribbon:
  eureka:
    enabled: false
fleet-location-ingest:
  ribbon:
    listOfServers: localhost:9006