server:
  port: 9000
spring:
  application:
    name: fleet-location-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
